//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SV.ClassServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassDto", Namespace="http://schemas.datacontract.org/2004/07/QLSV.WCF.InterfaceService")]
    [System.SerializableAttribute()]
    public partial class ClassDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLopField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaLop {
            get {
                return this.MaLopField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLopField, value) != true)) {
                    this.MaLopField = value;
                    this.RaisePropertyChanged("MaLop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLop {
            get {
                return this.TenLopField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLopField, value) != true)) {
                    this.TenLopField = value;
                    this.RaisePropertyChanged("TenLop");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClassServiceRef.IClassService")]
    public interface IClassService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/GetAllClasses", ReplyAction="http://tempuri.org/IClassService/GetAllClassesResponse")]
        QL_SV.ClassServiceRef.ClassDto[] GetAllClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/GetAllClasses", ReplyAction="http://tempuri.org/IClassService/GetAllClassesResponse")]
        System.Threading.Tasks.Task<QL_SV.ClassServiceRef.ClassDto[]> GetAllClassesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/AddClass", ReplyAction="http://tempuri.org/IClassService/AddClassResponse")]
        bool AddClass(QL_SV.ClassServiceRef.ClassDto classDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/AddClass", ReplyAction="http://tempuri.org/IClassService/AddClassResponse")]
        System.Threading.Tasks.Task<bool> AddClassAsync(QL_SV.ClassServiceRef.ClassDto classDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/UpdateClass", ReplyAction="http://tempuri.org/IClassService/UpdateClassResponse")]
        bool UpdateClass(string maLop, QL_SV.ClassServiceRef.ClassDto classDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/UpdateClass", ReplyAction="http://tempuri.org/IClassService/UpdateClassResponse")]
        System.Threading.Tasks.Task<bool> UpdateClassAsync(string maLop, QL_SV.ClassServiceRef.ClassDto classDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/DeleteClass", ReplyAction="http://tempuri.org/IClassService/DeleteClassResponse")]
        bool DeleteClass(string maLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/DeleteClass", ReplyAction="http://tempuri.org/IClassService/DeleteClassResponse")]
        System.Threading.Tasks.Task<bool> DeleteClassAsync(string maLop);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClassServiceChannel : QL_SV.ClassServiceRef.IClassService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassServiceClient : System.ServiceModel.ClientBase<QL_SV.ClassServiceRef.IClassService>, QL_SV.ClassServiceRef.IClassService {
        
        public ClassServiceClient() {
        }
        
        public ClassServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QL_SV.ClassServiceRef.ClassDto[] GetAllClasses() {
            return base.Channel.GetAllClasses();
        }
        
        public System.Threading.Tasks.Task<QL_SV.ClassServiceRef.ClassDto[]> GetAllClassesAsync() {
            return base.Channel.GetAllClassesAsync();
        }
        
        public bool AddClass(QL_SV.ClassServiceRef.ClassDto classDto) {
            return base.Channel.AddClass(classDto);
        }
        
        public System.Threading.Tasks.Task<bool> AddClassAsync(QL_SV.ClassServiceRef.ClassDto classDto) {
            return base.Channel.AddClassAsync(classDto);
        }
        
        public bool UpdateClass(string maLop, QL_SV.ClassServiceRef.ClassDto classDto) {
            return base.Channel.UpdateClass(maLop, classDto);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateClassAsync(string maLop, QL_SV.ClassServiceRef.ClassDto classDto) {
            return base.Channel.UpdateClassAsync(maLop, classDto);
        }
        
        public bool DeleteClass(string maLop) {
            return base.Channel.DeleteClass(maLop);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteClassAsync(string maLop) {
            return base.Channel.DeleteClassAsync(maLop);
        }
    }
}
