//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SV.FacultyServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacultyDto", Namespace="http://schemas.datacontract.org/2004/07/QL_SV.Service.InterfaceService")]
    [System.SerializableAttribute()]
    public partial class FacultyDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SdtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhoaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sdt {
            get {
                return this.SdtField;
            }
            set {
                if ((object.ReferenceEquals(this.SdtField, value) != true)) {
                    this.SdtField = value;
                    this.RaisePropertyChanged("Sdt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenKhoa {
            get {
                return this.TenKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhoaField, value) != true)) {
                    this.TenKhoaField = value;
                    this.RaisePropertyChanged("TenKhoa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacultyServiceRef.IFacultyService")]
    public interface IFacultyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/GetAllFaculties", ReplyAction="http://tempuri.org/IFacultyService/GetAllFacultiesResponse")]
        QL_SV.FacultyServiceRef.FacultyDto[] GetAllFaculties();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/GetAllFaculties", ReplyAction="http://tempuri.org/IFacultyService/GetAllFacultiesResponse")]
        System.Threading.Tasks.Task<QL_SV.FacultyServiceRef.FacultyDto[]> GetAllFacultiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/AddFaculty", ReplyAction="http://tempuri.org/IFacultyService/AddFacultyResponse")]
        bool AddFaculty(QL_SV.FacultyServiceRef.FacultyDto faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/AddFaculty", ReplyAction="http://tempuri.org/IFacultyService/AddFacultyResponse")]
        System.Threading.Tasks.Task<bool> AddFacultyAsync(QL_SV.FacultyServiceRef.FacultyDto faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/UpdateFaculty", ReplyAction="http://tempuri.org/IFacultyService/UpdateFacultyResponse")]
        bool UpdateFaculty(string maKhoa, QL_SV.FacultyServiceRef.FacultyDto faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/UpdateFaculty", ReplyAction="http://tempuri.org/IFacultyService/UpdateFacultyResponse")]
        System.Threading.Tasks.Task<bool> UpdateFacultyAsync(string maKhoa, QL_SV.FacultyServiceRef.FacultyDto faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/DeleteFaculty", ReplyAction="http://tempuri.org/IFacultyService/DeleteFacultyResponse")]
        bool DeleteFaculty(string maKhoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/DeleteFaculty", ReplyAction="http://tempuri.org/IFacultyService/DeleteFacultyResponse")]
        System.Threading.Tasks.Task<bool> DeleteFacultyAsync(string maKhoa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFacultyServiceChannel : QL_SV.FacultyServiceRef.IFacultyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacultyServiceClient : System.ServiceModel.ClientBase<QL_SV.FacultyServiceRef.IFacultyService>, QL_SV.FacultyServiceRef.IFacultyService {
        
        public FacultyServiceClient() {
        }
        
        public FacultyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacultyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacultyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacultyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QL_SV.FacultyServiceRef.FacultyDto[] GetAllFaculties() {
            return base.Channel.GetAllFaculties();
        }
        
        public System.Threading.Tasks.Task<QL_SV.FacultyServiceRef.FacultyDto[]> GetAllFacultiesAsync() {
            return base.Channel.GetAllFacultiesAsync();
        }
        
        public bool AddFaculty(QL_SV.FacultyServiceRef.FacultyDto faculty) {
            return base.Channel.AddFaculty(faculty);
        }
        
        public System.Threading.Tasks.Task<bool> AddFacultyAsync(QL_SV.FacultyServiceRef.FacultyDto faculty) {
            return base.Channel.AddFacultyAsync(faculty);
        }
        
        public bool UpdateFaculty(string maKhoa, QL_SV.FacultyServiceRef.FacultyDto faculty) {
            return base.Channel.UpdateFaculty(maKhoa, faculty);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateFacultyAsync(string maKhoa, QL_SV.FacultyServiceRef.FacultyDto faculty) {
            return base.Channel.UpdateFacultyAsync(maKhoa, faculty);
        }
        
        public bool DeleteFaculty(string maKhoa) {
            return base.Channel.DeleteFaculty(maKhoa);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteFacultyAsync(string maKhoa) {
            return base.Channel.DeleteFacultyAsync(maKhoa);
        }
    }
}
